
<div id="content_home_tabs">
	<ul>
		<li class="first ui-corner-top ui-state-default"><a href="#tabs-1"><?php echo $this->__('New Products') ?></a></li>
		<!--<li class="ui-corner-top ui-state-default" ><a href="#tabs-2"><?php /*echo $this->__('Featured Products') */?></a></li>
		<li class="ui-corner-top ui-state-default"><a href="#tabs-3"><?php /*echo $this->__("On Sale") */?></a></li>-->
	</ul>

    <style>
        .products-grid .product-name {
            margin: 0 !important;
        }

        .ui-tabs .ui-tabs-panel .products-grid li.item {
            width: 215px !important;
        }
    </style>

	<div id="tabs-1">

        <?php
		$_productCollection = Mage::getModel('catalog/product')
			->getCollection()
			->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
			->addAttributeToSelect('*')
			->addAttributeToFilter('category_id', array(
					array('finset' => '3'))
			)
			->addAttributeToSort('created_at', 'desc');
        ?>

        <ul class="products-grid span4">
			<?php $i=0; foreach ($_productCollection as $_product) { $i++; if($i>=9){ break; } ?>
                <li class="item">
					<?php if($i==1) { ?><h3 class="product-name"><a title="Motorola" href="<?php echo $_product->getProductUrl() ?>">
                        </a>
                        </h3><?php } ?>
                    <!--<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?><span> <?php echo $_product->getProduct_color_text() ?></span></a></h2>-->
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(301,214) ?>" width="301" height="214" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <p class="short_desc">  <?php $_description = $_product->getShortDescription();
						if(strlen($_description) <= 50)
						{
							echo $_description;
						}
						else{
							echo substr($_description,0,50).'...';
						}?></p>
					<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php endif; ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">

                        <a class="details" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo 'Details' ?>"><?php echo 'Details'; ?></a>
                    </div>
                    <div class="clear"></div>
					<?php if($i==1) { ?>
                        <div class="box-shadow"></div>
					<?php } ?>
                </li>
			<?php } ?>
        </ul>
        <?php /*echo $this->getChildHtml('ebajes_new_products_home_tab');*/?>
    </div>
	<!--<div id="tabs-2"><?php /*echo $this->getChildHtml('ebajes_featured_products_home_tab');*/?></div>
	<div id="tabs-3"><?php /*echo $this->getChildHtml('ebajes_sale_products_home_tab');*/?></div>-->

	<!--div id="tabs-1">New</div>
	<div id="tabs-2">Featured</div>
	<div id="tabs-3">Sale</div-->
</div>

	<script type="text/javascript">
		jQuery(function(){
			jQuery("#content_home_tabs").tabs();
		});
	</script>